### ISSUE TITLE
可以求一份后端SQL文件吗

### ISSUE THREAD

**Issue by Kiwamm** [lizhiweip/elderlyInsurance#1]
大佬，有后端sql文件吗

**Comment by lizhiweip** [comment]
不好意思啊，sql在原来的电脑上，找不到了，你可以通过实体类反向建立数据库

**Comment by Kiwamm** [comment]
好的，谢谢啦，已经退出来了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月9日(周日) 晚上11:01
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lizhiweip/elderlyInsurance] 可以求一份后端SQL文件吗 (Issue #1)




 
不好意思啊，sql在原来的电脑上，找不到了，你可以通过实体类反向建立数据库

**Comment by lizhiweip** [comment]
前端用微信开发者工具打开，邮件发送功能需要打开邮箱的一个权限

**Comment by Kiwamm** [comment]
> 前端用微信开发者工具打开，邮件发送功能需要打开邮箱的一个权限

okk
